title: Fireduino
email: ebonner@airmail.cc
description: Cloud-based temperature reporting using Arduino
theme: jekyll-theme-cayman

baseurl: /Fireduino
url: http://efjimm.github.io
github_username: efjimm
